services:
  app:
    image: php:8.3-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      TZ: Europe/Lisbon
    command: --default-time-zone='Europe/Lisbon'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  composer:
    image: composer:2
    container_name: laravel_composer
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_artisan
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

volumes:
  db_data:
